In [11]:
import numpy as np

In [15]:
#creating 1D & 2D array

num1D=[1,2,3]                      #creating list
print(num1D)                         #printing list 
num2D=[(1,2,3),("a",'b','c')]           #creating 2 list in one tuple
print(num2D)                            #printing
num1D=np.array(num1D)              #converting list to array
print(num1D)                      #printing 1D array 
num2D=np.array(num2D)             #converting list to array 
print(num2D)                     #printing 2D Array 

[1, 2, 3]
[(1, 2, 3), ('a', 'b', 'c')]
[1 2 3]
[['1' '2' '3']
 ['a' 'b' 'c']]


In [18]:
#printing n*n identity matrix


print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [58]:
np.random.rand(5)   #printing 3 random numbers 

array([0.15198961, 0.21034084, 0.58143153, 0.80963801, 0.63619195])

In [62]:
np.random.rand(2,2)            #

array([[0.60254427, 0.39023376],
       [0.20558444, 0.2619765 ]])

In [64]:
np.random.rand(2,2,5)

array([[[0.50161755, 0.79514941, 0.75758667, 0.48547219, 0.57513911],
        [0.35390227, 0.72333014, 0.29700136, 0.46562624, 0.00531716]],

       [[0.01942751, 0.91826862, 0.3507652 , 0.28400151, 0.59123167],
        [0.34501396, 0.21265316, 0.85468563, 0.95902422, 0.80108919]]])

In [65]:
np.random.uniform(1,10,5)

array([5.89032702, 1.38785516, 7.99454297, 2.9148008 , 5.64878031])

In [53]:
np.random.randint(50)

33

In [45]:
np.random.randint(4,7)

6

In [35]:
np.random.randint(1,11,5)

array([ 2,  5,  4, 10,  1])